# Generated by Django 3.1.3 on 2020-11-18 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalaccount',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_generalaccount', to=settings.AUTH_USER_MODEL, verbose_name='Создана пользователем'),
        ),
        migrations.AlterField(
            model_name='generalaccount',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_generalaccount_related', to=settings.AUTH_USER_MODEL, verbose_name='Последний изменивший пользователь'),
        ),
    ]
