# Generated by Django 3.1.3 on 2020-12-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201122_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalaccount',
            name='skills',
            field=models.JSONField(blank=True, default=dict, verbose_name='Навыки пользователя'),
        ),
    ]
