# Generated by Django 3.1.3 on 2021-01-03 21:44

import django.contrib.auth.models
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_generalaccount_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalaccount',
            options={'verbose_name': 'account', 'verbose_name_plural': 'accounts'},
        ),
        migrations.AlterModelManagers(
            name='generalaccount',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('active_accounts', users.models.AvailableObjectsManager()),
                ('active_recruiters_accounts', users.models.AvailableRecruiterManager()),
                ('active_applicants_accounts', users.models.AvailableApplicantsManager()),
            ],
        ),
        migrations.AddField(
            model_name='generalaccount',
            name='organization_description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание организации'),
        ),
        migrations.AddField(
            model_name='generalaccount',
            name='profile_file',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Файл профиля комапнии'),
        ),
        migrations.AlterField(
            model_name='generalaccount',
            name='account_type',
            field=models.CharField(choices=[('__APPLICANT__', 'Соискатель'), ('__HIRER__', 'Наниматель'), ('__ORGANIZATION__', 'Организация')], default='__APPLICANT__', help_text='Обозначает тип аккаунта', max_length=50, verbose_name='Тип аккаунта'),
        ),
        migrations.AlterField(
            model_name='generalaccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail address'),
        ),
    ]
