
VACANCY_STATUS_NEW = '__NEW__'
VACANCY_STATUS_APPROVED = '__APPROVED__'
VACANCY_STATUS_PUBLISHED = '__PUBLISHED__'
VACANCY_STATUS_UNPUBLISHED = '__UNPUBLISHED__'
VACANCY_STATUS_MODIFIED = '__MODIFIED__'
VACANCY_STATUS_REJECTED = '__REJECTED__'
VACANCY_STATUS_BLOCKED = '__BLOCKED__'
VACANCY_STATUS_ARCHIVED = '__ARCHIVED__'


VACANCY_STATUSES = (
    (VACANCY_STATUS_NEW, 'Новая'),
    (VACANCY_STATUS_APPROVED, 'Одобрена'),
    (VACANCY_STATUS_PUBLISHED, 'Опубликована'),
    (VACANCY_STATUS_UNPUBLISHED, 'Не опубликована'),
    (VACANCY_STATUS_MODIFIED, 'Изменена'),
    (VACANCY_STATUS_REJECTED, 'Отклонена'),
    (VACANCY_STATUS_BLOCKED, 'Заблокирована'),
    (VACANCY_STATUS_ARCHIVED, 'В архиве')
)
VACANCY_STATUSES_DICT = dict(VACANCY_STATUSES)


VACANCY_RESPOND_STATUS_NEW = '__NEW__'
VACANCY_RESPOND_STATUS_APPROVED = '__APPROVED__'
VACANCY_RESPOND_STATUS_REJECTED = '__REJECTED__'
VACANCY_RESPOND_STATUS_DONE = '__DONE__'
VACANCY_RESPOND_STATUS_FAIL = '__FAIL__'
VACANCY_RESPOND_STATUS_CANCELLED = '__CANCELLED__'
VACANCY_RESPOND_STATUS_WITHDRAWN = '__WITHDRAWN__'
VACANCY_RESPOND_STATUS_ARCHIVED = '__ARCHIVED__'


VACANCY_RESPOND_STATUSES = (
    (VACANCY_RESPOND_STATUS_NEW, 'Новый'),
    (VACANCY_RESPOND_STATUS_APPROVED, 'Одобрен'),
    (VACANCY_RESPOND_STATUS_REJECTED, 'Отклонен'),
    (VACANCY_RESPOND_STATUS_DONE, 'Выполнен'),
    (VACANCY_RESPOND_STATUS_FAIL, 'Не выполнен'),
    (VACANCY_RESPOND_STATUS_CANCELLED, 'Отменен'),
    (VACANCY_RESPOND_STATUS_WITHDRAWN, 'Отозван'),
    (VACANCY_RESPOND_STATUS_ARCHIVED, 'В архиве')
)
VACANCY_RESPOND_STATUSES_LIST = [
    VACANCY_RESPOND_STATUS[0] for VACANCY_RESPOND_STATUS in VACANCY_RESPOND_STATUSES
]
