# Generated by Django 3.1.3 on 2020-12-15 21:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='пометка удаленности')),
                ('additional_info', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Ключ навыка')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
