# Generated by Django 3.1.3 on 2020-12-30 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='пометка удаленности')),
                ('additional_info', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('status', models.CharField(choices=[('__NEW__', 'Новая'), ('__APPROVED__', 'Одобрена'), ('__PUBLISHED__', 'Опубликована'), ('__UNPUBLISHED__', 'Не опубликована'), ('__MODIFIED__', 'Изменена'), ('__REJECTED__', 'Отклонена'), ('__BLOCKED__', 'Заблокирована'), ('__ARCHIVED__', 'В архиве')], default='__NEW__', max_length=100, verbose_name='Статус')),
                ('title', models.CharField(max_length=1000, verbose_name='Название вакансии')),
                ('description', models.TextField(max_length=10000, verbose_name='Название вакансии')),
                ('salary', models.CharField(max_length=100, verbose_name='Зарплата')),
                ('location', models.CharField(max_length=1000, verbose_name='Локация')),
                ('description_file', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Логотип')),
                ('skills', models.JSONField(blank=True, default=dict, verbose_name='Требуемы навыки')),
                ('reject_reasons', models.JSONField(blank=True, default=dict, verbose_name='Причины блокировки')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_vacancy', to=settings.AUTH_USER_MODEL, verbose_name='Создана пользователем')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_vacancy_related', to=settings.AUTH_USER_MODEL, verbose_name='Последний изменивший пользователь')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruiter', related_query_name='recruiter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyRespond',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='пометка удаленности')),
                ('additional_info', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные настройки')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Дополнительная информация')),
                ('status', models.CharField(choices=[('__NEW__', 'Новый'), ('__APPROVED__', 'Одобрен'), ('__APPOINTED__', 'Назначен'), ('__REJECTED__', 'Отклонен'), ('__WITHDRAWN__', 'Отозван'), ('__ARCHIVED__', 'В архиве')], default='__NEW__', max_length=100, verbose_name='Статус')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_vacancyrespond', to=settings.AUTH_USER_MODEL, verbose_name='Создана пользователем')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_vacancyrespond_related', to=settings.AUTH_USER_MODEL, verbose_name='Последний изменивший пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.vacancy')),
            ],
            options={
                'unique_together': {('vacancy', 'account')},
            },
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responders',
            field=models.ManyToManyField(related_name='responders', related_query_name='responders', through='vacancies.VacancyRespond', to=settings.AUTH_USER_MODEL),
        ),
    ]
