# Generated by Django 3.1.3 on 2021-01-02 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyrespond',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Оценка проделанной работы'),
        ),
        migrations.AddField(
            model_name='vacancyrespond',
            name='recruiter_comment',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Коментрий нанимателя'),
        ),
        migrations.AlterField(
            model_name='vacancyrespond',
            name='status',
            field=models.CharField(choices=[('__NEW__', 'Новый'), ('__APPROVED__', 'Одобрен'), ('__REJECTED__', 'Отклонен'), ('__DONE__', 'Выполнен'), ('__FAIL__', 'Не выполнен'), ('__CANCELLED__', 'Отменен'), ('__WITHDRAWN__', 'Отозван'), ('__ARCHIVED__', 'В архиве')], default='__NEW__', max_length=100, verbose_name='Статус'),
        ),
    ]
