# Generated by Django 3.1.3 on 2021-01-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_auto_20210102_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='Описание вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancyrespond',
            name='recruiter_comment',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Коментрий нанимателя'),
        ),
    ]
